CREATE TABLE [dbo].[Author] (
    [AUTHOR_ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AUTHOR_DISPLAY_NAME] NVARCHAR (2048) NOT NULL,
    CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED ([AUTHOR_ID] ASC)
);

