CREATE TABLE [dbo].[Book] (
    [BOOK_ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AUTHOR_ID]         BIGINT          NOT NULL,
    [BOOK_TITLE]        NVARCHAR (2048) NOT NULL,
    [BOOK_SUMMARY]      NVARCHAR (MAX)  NULL,
    [BOOK_TOTAL_PAGES]  INT             NULL,
    [BOOK_RELEASE_DATE] DATE            NULL,
    [BOOK_ISBN]         NVARCHAR (32)   NULL,
    CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED ([BOOK_ID] ASC),
    CONSTRAINT [CK_Book_TOTAL_PAGES_IS_POSITIVE] CHECK ([BOOK_TOTAL_PAGES] IS NULL OR [BOOK_TOTAL_PAGES]>(0)),
    CONSTRAINT [FK_Book_Author] FOREIGN KEY ([AUTHOR_ID]) REFERENCES [dbo].[Author] ([AUTHOR_ID])
);



