//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookzilla.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookzillaEntities : DbContext
    {
        public BookzillaEntities()
            : base("name=BookzillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<v_BookSummary> v_BookSummary { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
    
        public virtual int p_BookUpdateInventory(Nullable<long> bOOK_ID, Nullable<int> qUANTITY_IN_STOCK)
        {
            var bOOK_IDParameter = bOOK_ID.HasValue ?
                new ObjectParameter("BOOK_ID", bOOK_ID) :
                new ObjectParameter("BOOK_ID", typeof(long));
    
            var qUANTITY_IN_STOCKParameter = qUANTITY_IN_STOCK.HasValue ?
                new ObjectParameter("QUANTITY_IN_STOCK", qUANTITY_IN_STOCK) :
                new ObjectParameter("QUANTITY_IN_STOCK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_BookUpdateInventory", bOOK_IDParameter, qUANTITY_IN_STOCKParameter);
        }
    
        public virtual ObjectResult<p_BookSearch_Result> p_BookSearch(string sEARCH_TEXT)
        {
            var sEARCH_TEXTParameter = sEARCH_TEXT != null ?
                new ObjectParameter("SEARCH_TEXT", sEARCH_TEXT) :
                new ObjectParameter("SEARCH_TEXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_BookSearch_Result>("p_BookSearch", sEARCH_TEXTParameter);
        }
    }
}
