//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookzilla.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BookSummary
    {
        public long BOOK_ID { get; set; }
        public string BOOK_TITLE { get; set; }
        public long AUTHOR_ID { get; set; }
        public string AUTHOR_DISPLAY_NAME { get; set; }
        public Nullable<System.DateTime> BOOK_RELEASE_DATE { get; set; }
        public string BOOK_ISBN { get; set; }
    }
}
